name: ios-simulator
on: [push, pull_request]
jobs:
  ios-iphone-simulator:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
<<<<<<< HEAD
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR ..
=======
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=SIMULATOR -DNCNN_SIMPLEOMP=ON ..
>>>>>>> 73319905989d63ee61f094b6e38d0a1beb4af4c1
    - name: build
      run: cmake --build build -j 2
